# Generated by Django 4.1.5 on 2023-01-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='name_en',
            field=models.CharField(max_length=221, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_ru',
            field=models.CharField(max_length=221, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_uz',
            field=models.CharField(max_length=221, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='text_uz',
            field=models.TextField(null=True),
        ),
    ]
